const rulesBase = {
  'arrow-spacing': 2,
  'block-spacing': 1,
  'brace-style': 1,
  camelcase: ['warn', { properties: 'always' }],
  'comma-dangle': [0, 'only-multiline'],
  'comma-spacing': 1,
  'comma-style': ['warn', 'last'],
  'default-case': 'error',
  'dot-location': ['warn', 'property'],
  'dot-notation': 0,
  'eol-last': 2,
  'func-call-spacing': 2,
  // deprecated in ESLint v8.53.0.
  // 'function-paren-newline': ['error', 'multiline-arguments'],
  // indent: ['warn', 2, { SwitchCase: 1, VariableDeclarator: 1, flatTernaryExpressions: false, offsetTernaryExpressions: false }],
  indent: 0,
  'jsx-quotes': ['warn', 'prefer-single'],
  'key-spacing': 1,
  'keyword-spacing': 1,
  'lines-between-class-members': 1,
  'max-len': ['warn', { code: 150 }],
  'new-cap': 0,
  'no-alert': 1,
  'no-async-promise-executor': 1,
  'no-case-declarations': 1,
  'no-confusing-arrow': 1,
  'no-console': 2,
  'no-const-assign': 2,
  'no-duplicate-imports': 1,
  'no-eval': 2,
  'no-extend-native': 2,
  'no-prototype-builtins': 1,
  'no-misleading-character-class': 0,
  'no-multiple-empty-lines': [1, { max: 1 }],
  'no-trailing-spaces': 1,
  'no-unneeded-ternary': 1,
  'no-unused-expressions': 1,
  'no-useless-catch': 1,
  'no-mixed-spaces-and-tabs': ['error', 'smart-tabs'],
  'no-useless-constructor': 1,
  'no-var': 1,
  'object-curly-spacing': [1, 'always'],
  'object-curly-newline': 1,
  'prefer-const': 1,
  'prefer-destructuring': ['warn', { array: true, object: true }],
  'prefer-rest-params': 1,
  'prefer-spread': 1,
  'prefer-template': 1,
  quotes: ['warn', 'single', { avoidEscape: true, allowTemplateLiterals: true }],
  'quote-props': ['warn', 'as-needed'],
  'rest-spread-spacing': 2,
  'spaced-comment': ['warn', 'always'],
  'space-before-function-paren': 'off',
  'switch-colon-spacing': 1,

  'react-hooks/rules-of-hooks': 'warn',
  'react-hooks/exhaustive-deps': 'warn',

  'jsx-a11y/click-events-have-key-events': 'off',
  'jsx-a11y/no-static-element-interactions': 'off',

  'no-restricted-imports': [
    'error',
    {
      paths: [
        {
          name: 'BrowserRouter',
          message: "Please import { FlexBrowserRouter } from '@flexiness/domain-lib-mobx-react-router' instead.",
        },
      ],
    },
  ],
}

const rulesReact = {
  'react/display-name': 2,
  'react/jsx-key': 2,
  'react/jsx-no-duplicate-props': 2,
  'react/jsx-no-useless-fragment': 1,
  'react/jsx-no-target-blank': 2,
  'react/prop-types': 0,
}

export { rulesBase, rulesReact }
